### PR TITLE
fixed shadow logo

### PR DESCRIPTION
**Pull request by MasterGordon**

### CODE REVIEW

**Comment by Lmakercoredoge** [comment]
I need to upload the token log, please let me know how to do it

**Comment by MasterGordon** [comment]
> I need to upload the token log, please let me know how to do it

If you want us to add you logo and get listed on IceCreamSwap please reach out to us via telegram

**Comment by Lmakercoredoge** [comment]
What is your Telegram ID?

**Comment by Lmakercoredoge** [comment]
Please check your telegram DM

**Comment by MasterGordon** [comment]
> What is your Telegram ID?

Just join our official group

**Comment by Lmakercoredoge** [comment]
Signed up for Ice Cream Swap Official

**Pull request merged**
